# Generated by Django 5.2.12 on 2026-03-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_customuser_address_customuser_admission_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_questions',
            field=models.IntegerField(default=10),
        ),
    ]
