# Generated by Django 5.2.12 on 2026-03-26 18:50

import django.db.models.deletion
from django.db import migrations, models


def fill_missing_question_subjects(apps, schema_editor):
    Question = apps.get_model('quiz', 'Question')
    Subject = apps.get_model('quiz', 'Subject')

    fallback_subject, _ = Subject.objects.get_or_create(name='General')

    for question in Question.objects.select_related('quiz', 'quiz__subject').all():
        if question.subject_id:
            continue
        if question.quiz_id and question.quiz and question.quiz.subject_id:
            question.subject_id = question.quiz.subject_id
        else:
            question.subject_id = fallback_subject.id
        question.save(update_fields=['subject'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_subject'),
    ]

    operations = [
        migrations.RunPython(fill_missing_question_subjects, noop_reverse),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject'),
        ),
    ]
